services:
  - type: web
    name: backend-api
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: SalesTrack
          property: connectionString
      - key: JwtSettings__Key
        value: 8QFtzF8MbUiNDBUdF0Pw/g==Hus33sS7y0aBBnbqqEkCuA==
  
  - type: web
    name: frontend-ui
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ApiBaseUrl
        value: https://backend-api.onrender.com

databases:
  - name: SalesTrack
    databaseName: SalesTrack
    user: postgres
    plan: admin

