services:
  - type: web
    name: salestrack-backend
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        value: postgresql://neondb_owner:npg_TJMUcg0dbk8q@ep-floral-mouse-a6enwgad-pooler.us-west-2.aws.neon.tech/neondb?sslmode=require
      - key: JwtSettings__Key
        value: 8QFtzF8MbUiNDBUdF0Pw/g==Hus33sS7y0aBBnbqqEkCuA==

  - type: web
    name: salestrack-frontend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ApiBaseUrl
        value: https://salestrack-backend.onrender.com
